---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config-pvc
  namespace: searxng
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data-pvc
  namespace: searxng
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-pvc
  namespace: searxng
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
